webroot/common/ui/js/model.config.js, webroot/config/physicaldevices/baremetal/ui/js/models/BaremetalInterfacesModel.js, webroot/config/physicaldevices/baremetal/ui/js/models/BaremetalModel.js, webroot/config/physicaldevices/baremetal/ui/js/views/BaremetalEditView.js
Baremetal page: Changes to use the new Editable Grid. Some fixes to Edit Config as well.
=> Changes to incorporate new editable grid.

webroot/common/ui/js/model.config.js, webroot/config/physicaldevices/baremetal/ui/js/models/BaremetalInterfacesModel.js, webroot/config/physicaldevices/baremetal/ui/js/models/BaremetalModel.js, webroot/config/physicaldevices/baremetal/ui/js/views/BaremetalEditView.js
Baremetal page: Changes to use the new Editable Grid. Some fixes to Edit Config as well.
=> Changes to incorporate new editable grid in baremetal page.

webroot/common/ui/js/sm.detail.tmpls.js, webroot/common/ui/js/sm.grid.config.js, webroot/common/ui/js/sm.labels.js, webroot/common/ui/js/sm.parsers.js, webroot/setting/sm/ui/js/views/ClusterListView.js, webroot/setting/sm/ui/js/views/ServerInventoryView.js, webroot/setting/sm/ui/js/views/ServerListView.js, webroot/setting/sm/ui/js/views/ServerMonitoringView.js, webroot/setting/sm/ui/js/views/ServerTabView.js
Change-Id: Ib42059ba8d041748fdd777e367462d49354f6bd6
=> Partial-Bug: #1440423 Implement scatter charts for clusters and servers

webroot/common/xml/featureList.xml
Related-Bug: #1440004
Change-Id: I6dac09f8da62c9df845cd6bf2831ef99f40f1f07
=> Adding parseFeatureReq require statement for contrail-web-server-manager

webroot/setting/sm/ui/js/views/ClusterTabView.js
Change-Id: I73b22265013b3236130c2e1091267b14d21d0ba2
=> Highlight servers tab by default for cluster page.

webroot/setting/sm/ui/js/views/ClusterTabView.js
Change-Id: Ib5e59d4de388c2967c5ee1c22f209eaa46796d49
=> Partial-Bug: #1459472 Networking monitoring issues on scale setup Pt 18

webroot/common/ui/js/sm.detail.tmpls.js, webroot/common/ui/js/sm.grid.config.js
Change-Id: I1ebf8c54556bb21a74b620f0d188094a1304f942
=> Closes-Bug: #1462140 Removed the link for Roels for Servers

webroot/common/ui/js/sm.detail.tmpls.js, webroot/common/ui/js/sm.grid.config.js, webroot/setting/sm/ui/js/views/ClusterTabView.js
Change-Id: I919f37b8962cf5f41cca4dc8ccb2529818c15d03
=> Closes-Bug: #1469454 - Performance/Usability Issues and code cleanup

webroot/setting/sm/ui/js/views/ClusterEditView.js, webroot/setting/sm/ui/js/views/ClusterListView.js, webroot/setting/sm/ui/js/views/ServerListView.js
Change-Id: Ib968d1f8b179caeef626e54cc334fac17d36a2e4
=> Partial-Bug: #1449727 Allow moving of popup windows.

webroot/common/ui/js/sm.model.config.js, webroot/setting/sm/ui/js/models/ClusterModel.js
Closes-Bug: #1472420 Set default value for minimum disk to be 256 in SM webUI
Change-Id: I7d3defe9d0dfa374ce2b8d6a5c10d3922930e5c3
=> Pull juniper/web-sm to absingla/web-sm

webroot/setting/sm/ui/js/views/ClusterEditView.js
Wizard related issues
1. Added a logic to make sure the the knockout binding is not applied multiple times
Change-Id: I04ce999e65dd0241f583c2ae6d1e8cad3c20eaa7
=> Closes-Bug: #1490736

webroot/common/ui/js/sm.labels.js, webroot/config/physicaldevices/baremetal/ui/js/views/BaremetalEditView.js, webroot/setting/sm/ui/js/views/ServerEditView.js, webroot/setting/sm/ui/test/ui/ClusterListView.test.js, webroot/setting/sm/ui/test/ui/ServerListView.test.js
Issues with Dropdown, Multiselect, and Combobox Views
1) Provide config to select the first element of dropdown view
2) Replace Grid dropdown, multiselect, input, and checkbox views with form views
3) Allow dropdown and multiselect option list to bind with data in model
4) Error should go away if correct value is selected in form dropdown views
Change-Id: I4207d77f6470dfe3ffd8cd5f99a38e5959defccb
=> Partial-Bug: #1495640

.pre-commit, webroot/test/ui/Gruntfile.js, webroot/test/ui/run_tests.sh
1. Adding support for git pre-commit hook to run UT on every commit.
2. to enable this feature, run grunt install-hook which will install the hook under your .git/hooks dir
3. 'git commit' command will run the tests first and will let commit on success
4. 'git commit --no-verify' to commit without running the tests.
Change-Id: If94b61c9fa1176769ce025854d231ab332a05646
=> Related-Bug: #1476413 pre-commit hook to run UT

webroot/common/ui/js/sm.constants.js, webroot/common/ui/js/sm.labels.js, webroot/common/ui/js/sm.model.config.js, webroot/setting/sm/ui/js/views/ServerEditView.js
Change-Id: I2d9fe4742156431639da685c0ea6517e9db0f5f9
=> Closes-Bug: #1560598 Added "ipmi_interface" field to SM UI.

webroot/test/ui/Gruntfile.js
Change-Id: I3f522f7f9b49d286cea8f4ed4d9a808cffaba641
Partial-Bug: #1571795
=> Added to Code Coverage to generate in Cobertura style report.

webroot/test/ui/Gruntfile.js, webroot/test/ui/sm.test.app.js
- moved build output dir to dist
- core.app.utils function will be used from co.test.app.utils
Change-Id: I314fcf985c7c6148a6c98c538765059855444793
=> Related-Bug #1526930 RequireJS optimization - bundle module

webroot/common/ui/js/sm.grid.config.js, webroot/common/ui/js/sm.messages.js, webroot/setting/sm/ui/js/views/ServerEditView.js
- Added server node health status
- Added 'No tags configured' message if tags are empty
Change-Id: Iaaf39ca6c1e9cac4cf34cb88c16d3a3dcb320458
=> Closes-Bug: #1594995, Closes-Bug: #1402932

webroot/common/ui/css/contrail.sm.css, webroot/common/ui/js/sm.grid.config.js, webroot/common/ui/js/sm.model.config.js, webroot/setting/sm/ui/js/views/ClusterEditView.js, webroot/setting/sm/ui/js/views/ServerEditView.js
1. Change haproxy_enable to false as default
2. Remove discovered bubble, change status color for server added = blue, server discovered =orange
3. Fix Servers grid does not refresh when we remove servers from a cluster
Change-Id: I2fadaef94fa9625a572aaedbe03998a6d9100a79
=> Closes-Bug: #1602028

webroot/common/ui/js/sm.app.js, webroot/common/ui/js/sm.grid.config.js, webroot/common/ui/js/sm.labels.js, webroot/common/ui/js/sm.model.config.js, webroot/common/ui/js/sm.parsers.js, webroot/menu.xml, webroot/setting/sm/ui/js/schemas/cluster.schema.js, webroot/setting/sm/ui/js/schemas/server.schema.js, webroot/setting/sm/ui/js/views/ClusterGridView.js, webroot/setting/sm/ui/js/views/ClusterListView.js, webroot/setting/sm/ui/js/views/ClusterTabView.js, webroot/setting/sm/ui/js/views/ServerGridView.js, webroot/setting/sm/ui/js/views/ServerListView.js, webroot/test/ui/Gruntfile.js, webroot/test/ui/sm.test.utils.js
Change-Id: I2deebd87d9b07290ef4b41949539cdf3b506b9e8
=> Closes-Bug: #1602902 Integrate json editor view on clusters and servers

webroot/menu.xml
Changing admin to cloudAdmin role in server-maneger menu.
Change-Id: I185120ea5a016095d28d429b62c40128ac164240
=> Related-Bug: #1559943

webroot/setting/sm/ui/js/views/ServerTabView.js
- Added renderOnActivate: true for Server Monitoring Tabs.
- Added check for Grid Id before applying refreshView.
Change-Id: I5c6c423bad38d6772279f9d9350f342261c6c663
=> Closes-Bug: #1605396

.eslintignore, .eslintrc.json
Add rc files for JS linter
Change-Id: Icba520f9526d2fbbef6e75da7151f4fb9035f0d0
Related-Bug: #1621196
=> Add Linting Runtime Configurations

webroot/common/ui/js/sm.grid.config.js, webroot/setting/sm/test/ui/views/ClusterTabView.test.js, webroot/setting/sm/ui/js/views/ClusterTabView.js, webroot/setting/sm/ui/js/views/ServerTabView.js
1. Clicking on a cluster then clicking the servers tabs does not show the chart; only see the chart when you resize the window
2. Clicking on a grid column with no value results in a error
Change-Id: Ief9a089b7bbb183176134ca2a2ff4fc9e3ef18c2
=> Closes-Bug: #1637614
